### ISSUE TITLE
not working with chrome

### ISSUE THREAD

**Issue by ghost** [R4meau/abDetector#1]
detection does not work in chrome.
firefox is ok
IE (latest) diplays addblockker message, but there is no blocker installed :(

**Comment by MaZZly** [comment]
Another way to simply add adblocker detection is to add `onerror="dosomething();"` to the script tag

and if the script is loaded asynchronously like:

``` javascript
var sa = document.createElement('script');
sa.type = 'text/javascript';
sa.async = true;
sa.src = '//adnetwork/ads.js';
```

you can easily add 

``` javascript
sa.onerror = function() {
    var adBlocked = true;
};
```

**Comment by meaudotme** [comment]
@comtronix Hi there!
Sorry to hear that, but I made it using Chrome (Version 48.0.2564.109 (64-bit)), so it works fine for me, mind sharing your Chrome version?
As for IE, I have to admit, I never tested it there, I will definitely look through it. Thanks for the feedback.

@MaZZly Hello!
I tried implementing your suggestion but it didn't work against the current adblockers. If you are sure that it works, please, try implementing it and send me a pull request. Thank you.
