### ISSUE TITLE
Using on HTTPS server browser blocks abDetector.min.js

### ISSUE THREAD

**Issue by qfreiman** [R4meau/abDetector#2]
when the script is used on HTTPS the  browser (google Chrome) blocks the page http://1781.com/ads.html and other sites it loads.

A fix would be appreciated

**Comment by qfreiman** [comment]
![https](https://cloud.githubusercontent.com/assets/22255341/18607701/ae121e22-7ce5-11e6-83b3-6f00297b48d2.PNG)

**Comment by meaudotme** [comment]
Okay, I suppose I'll have to make it detect the protocol too then. I'm going to try that and I'll let you know. ~~I hope you can give me some feedback afterward because at the moment I have no way of knowing if it works.~~

**Comment by meaudotme** [comment]
@Qcraft Fix pushed. Please, close this issue if it's working fine for you too. Otherwise I'll just close it in 24 hours.

**Comment by qfreiman** [comment]
Thanks for the fix!
works very well.

**Comment by meaudotme** [comment]
You're welcome. Thanks to you for using my script.
