### ISSUE TITLE
Google Safe Browsing issue 

### ISSUE THREAD

**Issue by qfreiman** [R4meau/abDetector#3]
![chrome virus](https://cloud.githubusercontent.com/assets/22255341/19118371/420572c8-8b2d-11e6-8d3d-3c7b52fe8296.PNG)

When using google chrome occasionally it will display the message pictured above and when you reload the page it will go away and then sometimes come back after a few page reloadings

I hope you can fix this 🤓
thanks. 😀

**Comment by meaudotme** [comment]
Haha, will work on that.

**Comment by meaudotme** [comment]
@Qcraft Fix pushed. If everything's okay on your side, please close this issue.

**Comment by qfreiman** [comment]
thanks for the fix  :+1: :)
